-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 11:24:43 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema funko_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema funko_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `funko_schema` DEFAULT CHARACTER SET utf8 ;
USE `funko_schema` ;

-- -----------------------------------------------------
-- Table `funko_schema`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`category` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `category_description` VARCHAR(255) NULL,
  PRIMARY KEY (`category_id`),
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funko_schema`.`licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`licence` (
  `licence_id` INT NOT NULL AUTO_INCREMENT,
  `licence_name` VARCHAR(45) NOT NULL,
  `licence_description` VARCHAR(255) NOT NULL,
  `licence_image` VARCHAR(255) NULL,
  PRIMARY KEY (`licence_id`),
  UNIQUE INDEX `licence_id_UNIQUE` (`licence_id` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `funko_schema`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`product` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(60) NOT NULL,
  `product_description` VARCHAR(255) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL,
  `discount` INT NULL,
  `sku` VARCHAR(30) NOT NULL,
  `dues` INT NULL,
  `image_front` VARCHAR(200) NOT NULL,
  `image_back` VARCHAR(200) NOT NULL,
  `create_time` TIMESTAMP NULL,
  `category_id` INT NOT NULL,
  `licence_id` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  UNIQUE INDEX `product_id_UNIQUE` (`product_id` ASC) VISIBLE,
  INDEX `fk_product_category_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_product_licence1_idx` (`licence_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `funko_schema`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_licence1`
    FOREIGN KEY (`licence_id`)
    REFERENCES `funko_schema`.`licence` (`licence_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `funko_schema`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `funko_schema`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL,
  `lastname` VARCHAR(80) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

 